baseURL = 'https://r4sso.github.io'
languageCode = 'en-us'
title = 'r4sso.github.io'
theme = "myTheme"

[params]
    author = "r4sso"
    info = "Penetration Tester"
    desc = "This site under development"
    avatarurl = "https://hugo-coder.netlify.app/images/avatar.jpg"
    audio = "https://cdn-124.anonfiles.com/Q4ffJdPayc/5c68d140-1672674707/The%20Captain%20General-240GIoXuRUk.mp3"
  

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[social]
    twitter="r4ssonull"
    github="r4sso"
    instagram=""
    mail=""